name: Installation Tests

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        # TODO: How to run on e.g. mac arm64 vs x64
        settings:
          - host: macos-latest
          - host: ubuntu-latest
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Could matrix this, but idk
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn run test
