name: Installation and Benchmarks

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  benchmark:
    strategy:
      matrix:
        # TODO: How do i test darwin-arm64
        # TODO: Test linux-x64-musl
        settings:
          - host: macos-latest # test darwin-x64
          - host: ubuntu-latest # test linux-x64-gnu
          - host: windows-latest # win32-x64-msvc
    runs-on: ${{ matrix.settings.host }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Could matrix this, but idk
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn run test
      - name: Benchmark
        run: node ./benchmark/benchmark.mjs >> $GITHUB_STEP_SUMMARY
